# Generated by Django 3.1.7 on 2021-03-04 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('MOD', 'на модерации'), ('PUB', 'опубликован'), ('REJ', 'отклонен')], max_length=3)),
            ],
        ),
    ]
